// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRentalSystem.Data;

#nullable disable

namespace MovieRentalSystem.Migrations
{
    [DbContext(typeof(VideoRentalContext))]
    partial class VideoRentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MovieRentalSystem.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adamadamiak@gmail.com",
                            FirstName = "Adam",
                            LastName = "Adamiak",
                            Phone = "123456789",
                            RegisteredDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "ewaewiak@protonmail.com",
                            FirstName = "Ewa",
                            LastName = "Ewiak",
                            Phone = "987654321",
                            RegisteredDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A more realistic and at the same time a bit psychedelic depiction of war and violence",
                            Director = "Elem Klimov",
                            Genre = "Drama",
                            IsAvailable = true,
                            PricePerDay = 10.00m,
                            Title = "Come and See",
                            Year = 1985
                        },
                        new
                        {
                            Id = 2,
                            Description = "People argue over a death sentence.",
                            Director = "Sidney Lumet",
                            Genre = "Drama",
                            IsAvailable = true,
                            PricePerDay = 10.00m,
                            Title = "12 Angry Men",
                            Year = 1957
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mafia family saga",
                            Director = "Francis Ford Coppola",
                            Genre = "Drama",
                            IsAvailable = true,
                            PricePerDay = 10.00m,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 4,
                            Description = "A naive young man witnesses an escalation of violence in his small hometown following the arrival of a mysterious circus attraction.",
                            Director = "Béla Tarr",
                            Genre = "Drama",
                            IsAvailable = true,
                            PricePerDay = 10.00m,
                            Title = "Werckmeister harmóniák",
                            Year = 2000
                        },
                        new
                        {
                            Id = 5,
                            Description = "Batman vs Joker",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            IsAvailable = true,
                            PricePerDay = 10.00m,
                            Title = "The Dark Knight",
                            Year = 2008
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovieId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Rental", b =>
                {
                    b.HasOne("MovieRentalSystem.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRentalSystem.Models.Movie", "Movie")
                        .WithMany("Rentals")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Customer", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Movie", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
